In [6]:
import keras

from keras.applications.vgg16 import VGG16
from keras.applications import vgg16
from keras import models, Model

from keras.models import load_model
vgg16_model = load_model('vgg.h5',compile=False)


#vgg16_model = keras.applications.vgg16.VGG16()

In [10]:
from keras.models import Sequential
from keras.layers import Dense

In [11]:
model = Sequential()

for layer in vgg16_model.layers[:-1]:
    model.add(layer)

model.layers.pop()


# Freeze the layers 
for layer in model.layers:
    layer.trainable = False


# Add 'softmax' instead of earlier 'prediction' layer.
model.add(Dense(300, activation='relu'))


# Check the summary, and yes new layer has been added. 

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)      

In [19]:
model.save('300model.h5')

In [14]:
from keras.applications.vgg16 import preprocess_input
import cv2
import numpy as np
image = cv2.imread('D:\\ML\\Visual_Search\\res.jpg')
img_data = np.expand_dims(image, axis=0)
img_data = preprocess_input(img_data)


feat = model.predict(img_data)

In [18]:
feat

array([[7.30312824e-01, 3.72888654e-01, 7.97425285e-02, 0.00000000e+00,
        4.42757696e-01, 9.53126431e-01, 6.11105859e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.22814946e-01,
        6.94754899e-01, 0.00000000e+00, 0.00000000e+00, 1.96128821e+00,
        1.62833321e+00, 0.00000000e+00, 1.33559203e+00, 3.23974878e-01,
        2.00750399e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.96543121e-01, 1.78450096e+00, 1.01733398e+00, 0.00000000e+00,
        0.00000000e+00, 5.48046649e-01, 5.44575095e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.67106855e+00, 1.16720128e+00,
        0.00000000e+00, 0.00000000e+00, 1.21850878e-01, 0.00000000e+00,
        7.33863711e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.05140649e-01,
        0.00000000e+00, 1.79832309e-01, 2.68133044e-01, 0.00000000e+00,
        3.30084383e-01, 2.04046893e+00, 0.00000000e+00, 0.000000

In [1]:

from flask import Flask
from flask_mysqldb import MySQL

app = Flask(__name__)
app.config['MYSQL_USER'] = 'sql5390354'
app.config['MYSQL_PASSWORD'] = 'XZG3lajnMj'
app.config['MYSQL_HOST'] = 'sql5.freemysqlhosting.net'
app.config['MYSQL_DB'] = 'sql5390354'
#app.config['MYSQL_CURSORCLASS'] = 'DictCursor'


mysql = MySQL(app)


In [2]:
with app.app_context():
    cur = mysql.connection.cursor()
    cur.execute('''SELECT * FROM features''')
    images_features = list(cur.fetchall())
    print(images_features)
    print('__________________')

[(Decimal('1.18732700000000000000'), Decimal('1.88728870000000000000'), Decimal('0E-20'), Decimal('0.01842229000000000000'), Decimal('0E-20'), Decimal('2.56778220000000000000'), Decimal('0E-20'), Decimal('2.03117750000000000000'), Decimal('0E-20'), Decimal('0.06673598000000000000'), Decimal('0E-20'), Decimal('0.24138660000000000000'), Decimal('0.06399563000000000000'), Decimal('0E-20'), Decimal('0E-20'), Decimal('2.91566900000000000000'), Decimal('1.30419770000000000000'), Decimal('0.28891397000000000000'), Decimal('0.45605090000000000000'), Decimal('0E-20'), Decimal('0.69501734000000000000'), Decimal('0E-20'), Decimal('0E-20'), Decimal('0E-20'), Decimal('0E-20'), Decimal('0.98335440000000000000'), Decimal('1.15518950000000000000'), Decimal('0E-20'), Decimal('0E-20'), Decimal('0.29030310000000000000'), Decimal('0E-20'), Decimal('1.49822990000000000000'), Decimal('0E-20'), Decimal('0E-20'), Decimal('1.66142740000000000000'), Decimal('0.38362288000000000000'), Decimal('0E-20'), Decimal('

In [123]:
d = []
a = []
d = []
import re
for i in images_features:
    for j in i:
        #((points,),) = j
        a.append(float("{:.32f}".format(j)))
    d.append(a)
    a = []

In [124]:
d = np.array(d)

In [125]:
d

array([[1.187327  , 1.8872887 , 0.        , ..., 0.05864711, 0.50022006,
        0.46261242],
       [0.        , 0.        , 0.        , ..., 0.30357975, 0.80734766,
        0.5259579 ],
       [0.5388224 , 0.        , 1.617509  , ..., 0.57250947, 0.5541767 ,
        0.        ],
       ...,
       [1.2573043 , 1.9026059 , 0.29748443, ..., 0.5466925 , 0.3318444 ,
        0.95496833],
       [1.4377596 , 2.1612275 , 0.        , ..., 0.        , 0.3326387 ,
        0.618551  ],
       [0.6615087 , 0.75748795, 0.07165904, ..., 0.        , 0.50974923,
        1.4779649 ]])

In [126]:

import pandas as pd
e = pd.read_csv('d:/ml/visual_search/300Feat.csv')
e = np.array(e)


In [127]:
e

array([[0.        , 0.        , 0.        , ..., 0.30357975, 0.80734766,
        0.5259579 ],
       [0.5388224 , 0.        , 1.617509  , ..., 0.57250947, 0.5541767 ,
        0.        ],
       [0.        , 0.        , 0.76184124, ..., 0.82484376, 1.6429682 ,
        0.27498603],
       ...,
       [1.2573043 , 1.9026059 , 0.29748443, ..., 0.5466925 , 0.3318444 ,
        0.95496833],
       [1.4377596 , 2.1612275 , 0.        , ..., 0.        , 0.3326387 ,
        0.618551  ],
       [0.6615087 , 0.75748795, 0.07165904, ..., 0.        , 0.50974923,
        1.4779649 ]])

In [120]:
import numpy as np
s = np.array(d[1]) - np.array(e[0])

In [121]:
c=0
x = 0
for f in s:
    if f != x:
        c+=1
c

35

In [130]:
for i in range(300):
    print(d[1][i])
    print(float("{:.32f}".format(e[0][i])))
    print("________")

0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
2.1087842
2.1087842
________
0.36421636
0.36421636
________
0.8342291
0.8342291
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
0.16506828
0.16506828
________
0.0
0.0
________
0.0
0.0
________
0.20530504
0.20530504
________
3.4722662
3.4722662000000004
________
1.4901495
1.4901495
________
0.0
0.0
________
0.88776225
0.88776225
________
0.0
0.0
________
1.4214364
1.4214364
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
1.3873342
1.3873342
________
0.735759
0.735759
________
1.197203
1.197203
________
0.0
0.0
________
0.0
0.0
________
0.15158805
0.15158805
________
2.3695369
2.3695369
________
0.0
0.0
________
1.1322186
1.1322186
________
0.7320626
0.7320626
________
0.80875635
0.80875635
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
0.0
0.0
________
2.0304947
2.0304947
________
0.0
0.0
________
0.0
0.0
________
0.

In [64]:
from keras.models import load_model
MODEL_PATH = 'd:/ml/visual_search/300model.h5'
model = load_model(MODEL_PATH)


In [92]:
from keras.applications.vgg16 import preprocess_input
import cv2
img_data = cv2.imread('C:\\Users\\khali\\PycharmProjects\\Scrape\\scrap\\carrefour\\carrefour\\prod\\new\\Abu Auf Pure Cocoa Powder 250g .jpg')
img_data = cv2.resize(img_data, (224,224))

img_data = np.expand_dims(img_data, axis=0)

img_data = preprocess_input(img_data)


new_im_pred = model.predict(img_data)


new_im_pred = np.array(new_im_pred)

In [93]:
new_im_pred = np.float32(new_im_pred)

In [131]:
pred = []

In [134]:
pred.append(new_im_pred) 

In [136]:
import pickle

In [138]:
with open("database.pickle", "wb") as f:
    pickle.dump(pred, f, pickle.HIGHEST_PROTOCOL)

In [140]:
with open('database.pickle', 'rb') as pickle_file:
    pca = pickle.load(pickle_file)

In [144]:
pca

[array([[1.187327  , 1.8872887 , 0.        , 0.01842229, 0.        ,
         2.5677822 , 0.        , 2.0311775 , 0.        , 0.06673598,
         0.        , 0.2413866 , 0.06399563, 0.        , 0.        ,
         2.915669  , 1.3041977 , 0.28891397, 0.4560509 , 0.        ,
         0.69501734, 0.        , 0.        , 0.        , 0.        ,
         0.9833544 , 1.1551895 , 0.        , 0.        , 0.2903031 ,
         0.        , 1.4982299 , 0.        , 0.        , 1.6614274 ,
         0.38362288, 0.        , 0.        , 0.        , 0.03970545,
         0.        , 0.        , 1.6544489 , 0.        , 0.        ,
         0.        , 0.25743717, 1.5342159 , 0.        , 1.7385576 ,
         1.1857955 , 0.        , 0.17726116, 0.        , 0.        ,
         0.        , 0.14900443, 0.        , 0.        , 0.69255203,
         0.        , 0.        , 0.69815516, 0.        , 0.7802645 ,
         0.        , 1.4361981 , 0.        , 0.28691804, 0.        ,
         0.        , 1.532937  , 0